name: End-to-end tests (containerd)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: |
          pip3 install --user --upgrade j2cli
          j2 --version

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup kind cluster
        run: hack/e2e-kind-cluster-setup.sh

      - name: Test provisioning examples
        run: e2e/test-provisioning-examples.sh

      - name: Run e2e tests
        env:
          KUBECONFIG: /home/runner/.kube/config
          LOWER_DEVICE: eth1
        run: make e2e/test

      - name: Cleanup cluster
        run: |
          kind delete cluster           # gracefully remove the cluster
          docker rm -f $(docker ps -qa) # remove the registry + any leftover
